name: JS

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: /home/runner/work/unipept/unipept/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Install dependencies
      run: |
        yarn install
    - name: Test
      run: |
        yarn test --ci --runInBand