version: '3.3'

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: 172.17.0.1
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: unipept
    restart: always
    networks:
      frontend:
        ipv4_address: 172.20.0.2
  app:
    build: ./unipept-application
    command: sleep infinity
    ports:
      - '5000:5000'
    network_mode: "host"
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace
  