version: '3.7'

services:
  db:
    build: ./unipept-db
    environment:
      MYSQL_ROOT_PASSWORD: unipept
      MYSQL_DATABASE: unipept
      MYSQL_USER: unipept
      MYSQL_PASSWORD: unipept
    restart: always
    ports:
      - "3306:3306"
    hostname: mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: unipept
    restart: always
  app:
    depends_on:
      - db
    build: ./unipept-application
    command: sleep infinity
    ports:
      - '5000:5000'
    network_mode: "host"
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ..:/workspace
  
